import type { ProviderType } from "@/db/types";
import type { ProviderMeta } from "./provider-meta-types";

/** 低频使用的 provider 配置（perplexity / together / xai / bedrock / github-models / custom） */
export const PROVIDER_DEFS_EXTRA: Record<Extract<ProviderType, "perplexity" | "together" | "xai" | "bedrock" | "github-models" | "custom">, ProviderMeta> = {
  perplexity: {
    type: "perplexity",
    displayName: "Perplexity",
    description: "Perplexity 搜索与推理模型",
    defaultBaseUrl: "https://api.perplexity.ai",
    requiresApiKey: true,
    requiresBaseUrl: false,
    supportsModelFetch: false,
    builtIn: true,
    fields: [],
    knownModels: [
      "sonar-pro",
      "sonar",
      "sonar-reasoning-pro",
      "sonar-reasoning",
    ],
  },
  together: {
    type: "together",
    displayName: "Together",
    description: "Together 开源模型 API",
    defaultBaseUrl: "https://api.together.xyz",
    requiresApiKey: true,
    requiresBaseUrl: false,
    supportsModelFetch: true,
    builtIn: true,
    fields: [],
    knownModels: [
      "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
      "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
      "mistralai/Mixtral-8x22B-Instruct-v0.1",
      "Qwen/Qwen2.5-72B-Instruct-Turbo",
    ],
  },
  xai: {
    type: "xai",
    displayName: "xAI",
    description: "xAI Grok 模型",
    defaultBaseUrl: "https://api.x.ai",
    requiresApiKey: true,
    requiresBaseUrl: false,
    supportsModelFetch: false,
    builtIn: true,
    fields: [],
    knownModels: [
      "grok-2",
      "grok-2-mini",
    ],
  },
  bedrock: {
    type: "bedrock",
    displayName: "AWS Bedrock",
    description: "AWS 托管的多厂商模型",
    requiresApiKey: false,
    requiresBaseUrl: false,
    supportsModelFetch: false,
    builtIn: false,
    fields: [
      { key: "aws_region", label: "AWS Region", type: "text", placeholder: "us-east-1", required: true },
      { key: "aws_access_key_id", label: "Access Key ID", type: "password", required: true },
      { key: "aws_secret_access_key", label: "Secret Access Key", type: "password", required: true },
    ],
    knownModels: [
      "anthropic.claude-3-5-sonnet-20241022-v2:0",
      "anthropic.claude-3-haiku-20240307-v1:0",
      "amazon.nova-pro-v1:0",
      "amazon.nova-lite-v1:0",
    ],
  },
  "github-models": {
    type: "github-models",
    displayName: "GitHub Models",
    description: "GitHub 推理服务模型",
    defaultBaseUrl: "https://models.inference.ai.azure.com",
    requiresApiKey: true,
    requiresBaseUrl: false,
    supportsModelFetch: true,
    builtIn: false,
    fields: [],
    knownModels: [
      "gpt-4o",
      "gpt-4o-mini",
      "Meta-Llama-3.1-405B-Instruct",
      "Mistral-Large",
    ],
  },
  custom: {
    type: "custom",
    displayName: "OpenAI Compatible",
    description: "兼容 OpenAI API 的自定义端点",
    requiresApiKey: false,
    requiresBaseUrl: true,
    supportsModelFetch: true,
    builtIn: false,
    fields: [],
    knownModels: [],
  },
};
